version: '3.8'
services:
  xrp-payment-app:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SPRING_APPLICATION_NAME: xrp-payment-app
      XRPL_TESTNET_WS_URL: ${XRPL_TESTNET_WS_URL}
      XRPL_TESTNET_HTTP_URL: ${XRPL_TESTNET_HTTP_URL}
      XRPL_SENDER_ADDRESS: ${XRPL_SENDER_ADDRESS}
      XRPL_SENDER_SECRET: ${XRPL_SENDER_SECRET}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      XAMAN_API_KEY: ${XAMAN_API_KEY}
      XAMAN_API_SECRET: ${XAMAN_API_SECRET}
      XAMAN_API_V1_BASE_URL: ${XAMAN_API_V1_BASE_URL}
      XAMAN_CALLBACK_URL: ${XAMAN_CALLBACK_URL}
    depends_on:
      - db
    networks:
      - service-network

  db:
    image: postgres:15
    container_name: xrp-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - xrp-data:/var/lib/postgresql/data
    networks:
      - service-network

networks:
  service-network:
    name: service-network

volumes:
  xrp-data: